name: Validate

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set up JDK 25
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"

  check-formatting:
    runs-on: ubuntu-latest
    needs: setup
  
    steps:
      - name: Check formatting
        run: ./mvnw spotless:check

  compile:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Compile
        run: ./mvnw compile

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: ./mvnw verify
